[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--no-frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-nextjs"
